server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9021/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: trade-capture
          uri: lb://trade-capture
          predicates:
            - Path=/capture/**
          filters:
            - RewritePath=/capture/(?<path>.*), /$\{path}
        - id: trade-query
          uri: lb://trade-query
          predicates:
            - Path=/query/**
          filters:
            - RewritePath=/query/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v2/api-docs/**
          filters:
            - RewritePath=/v2/api-docs/(?<path>.*), /$\{path}/v2/api-docs